/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pl.moderr.eduscript;

import org.junit.jupiter.api.Test;
import pl.moderr.eduscript.app.App;

import static org.junit.jupiter.api.Assertions.assertNotNull;

class AppTest {
  @Test
  void appHasAGreeting() {
    App classUnderTest = new App();
    assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
  }
}
